config/routes.rb
Rails.application.routes.draw do
  resources :artists
  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks' }

  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup

  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :donations, :concerns => :paginatable

  get 'home/index'

  root to: 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :artist

  validates :amount, numericality: { less_than: 1_000_000, allow_nil: true }

  class << self
    # ensures the following (for 2+ donations):
    #  - at least one donation if one exists
    #  - at least one request
    #  - first element is latest donation if one exists, latest request if none exist
    #  - second element is latest or 2nd latest request
    def present(donations)
      first_donation_index = donations.index { |d| d.request == false }
      if first_donation_index

        if first_donation_index.nonzero?
          donation = donations.delete_at(first_donation_index)
          donations.unshift(donation)
        end

        ensure_second_is_request(donations)
      else
        donation = order(id: :desc).find_by(request: false)
        if donation
          donations.pop
          donations.unshift(donation)
        end
      end
      donations
    end

    private

    def ensure_second_is_request(donations)
      return if donations.second.request
      first_request_index = donations.index { |d| d.request == true }

      request = if first_request_index.nil?
                  donations.pop
                  order(id: :desc).find_by(request: true)
                else
                  donations.delete_at(first_request_index)
                end

      donations.insert(1, request)
    end
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :set_donation, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /donations
  # GET /donations.json
  def index
    @donations = Donation.all
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  def new
    @donation = Donation.new
  end

  # GET /donations/1/edit
  def edit
  end

  # POST /donations
  # POST /donations.json
  def create
    @donation = Donation.new(donation_params)

    respond_to do |format|
      if @donation.save
        format.html { redirect_to @donation, notice: 'Donation was successfully created.' }
        format.json { render :show, status: :created, location: @donation }
      else
        format.html { render :new }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /donations/1
  # PATCH/PUT /donations/1.json
  def update
    respond_to do |format|
      if @donation.update(donation_params)
        format.html { redirect_to @donation, notice: 'Donation was successfully updated.' }
        format.json { render :show, status: :ok, location: @donation }
      else
        format.html { render :edit }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation.destroy
    respond_to do |format|
      format.html { redirect_to donations_url, notice: 'Donation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_donation
      @donation = Donation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def donation_params
      params.require(:donation).permit(:request, :artist_id, :artist_name, :artist_website, :artist_facebook, :artist_twitter, :artist_bandcamp, :artist_instagram, :artist_snapchat, :amount, :comment, :youtube_video_id, :youtube_error_code)
    end
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/views/donations/_form.html.erb
<%= form_for(donation) do |f| %>
  <% if donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(donation.errors.count, "error") %> prohibited this donation from being saved:</h2>

      <ul>
      <% donation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :request %>
    <%= f.check_box :request %>
  </div>

  <div class="field">
    <%= f.label :artist_id %>
    <%= f.number_field :artist_id %>
  </div>

  <div class="field">
    <%= f.label :artist_name %>
    <%= f.text_field :artist_name %>
  </div>

  <div class="field">
    <%= f.label :artist_website %>
    <%= f.text_field :artist_website %>
  </div>

  <div class="field">
    <%= f.label :artist_facebook %>
    <%= f.text_field :artist_facebook %>
  </div>

  <div class="field">
    <%= f.label :artist_twitter %>
    <%= f.text_field :artist_twitter %>
  </div>

  <div class="field">
    <%= f.label :artist_bandcamp %>
    <%= f.text_field :artist_bandcamp %>
  </div>

  <div class="field">
    <%= f.label :artist_instagram %>
    <%= f.text_field :artist_instagram %>
  </div>

  <div class="field">
    <%= f.label :artist_snapchat %>
    <%= f.text_field :artist_snapchat %>
  </div>

  <div class="field">
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="field">
    <%= f.label :youtube_video_id %>
    <%= f.text_field :youtube_video_id %>
  </div>

  <div class="field">
    <%= f.label :youtube_error_code %>
    <%= f.number_field :youtube_error_code %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Show', @donation %> |
<%= link_to 'Back', donations_path %>

app/views/donations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Donations</h1>

<table id="donations">
  <thead>
    <tr>
      <th>Request</th>
      <th>Artist</th>
      <th>Artist name</th>
      <th>Artist website</th>
      <th>Artist facebook</th>
      <th>Artist twitter</th>
      <th>Artist bandcamp</th>
      <th>Artist instagram</th>
      <th>Artist snapchat</th>
      <th>Amount</th>
      <th>Comment</th>
      <th>Youtube video</th>
      <th>Youtube error code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @donations.each do |donation| %>
      <tr>
        <td><%= donation.request %></td>
        <td><%= donation.artist_id %></td>
        <td><%= donation.artist_name %></td>
        <td><%= donation.artist_website %></td>
        <td><%= donation.artist_facebook %></td>
        <td><%= donation.artist_twitter %></td>
        <td><%= donation.artist_bandcamp %></td>
        <td><%= donation.artist_instagram %></td>
        <td><%= donation.artist_snapchat %></td>
        <td><%= donation.amount %></td>
        <td><%= donation.comment %></td>
        <td><%= donation.youtube_video_id %></td>
        <td><%= donation.youtube_error_code %></td>
        <td><%= link_to 'Show', donation %></td>
        <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
        <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New Donation</h1>

<%= render 'form', donation: @donation %>

<%= link_to 'Back', donations_path %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Request:</strong>
  <%= @donation.request %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @donation.artist_id %>
</p>

<p>
  <strong>Artist name:</strong>
  <%= @donation.artist_name %>
</p>

<p>
  <strong>Artist website:</strong>
  <%= @donation.artist_website %>
</p>

<p>
  <strong>Artist facebook:</strong>
  <%= @donation.artist_facebook %>
</p>

<p>
  <strong>Artist twitter:</strong>
  <%= @donation.artist_twitter %>
</p>

<p>
  <strong>Artist bandcamp:</strong>
  <%= @donation.artist_bandcamp %>
</p>

<p>
  <strong>Artist instagram:</strong>
  <%= @donation.artist_instagram %>
</p>

<p>
  <strong>Artist snapchat:</strong>
  <%= @donation.artist_snapchat %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @donation.amount %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @donation.comment %>
</p>

<p>
  <strong>Youtube video:</strong>
  <%= @donation.youtube_video_id %>
</p>

<p>
  <strong>Youtube error code:</strong>
  <%= @donation.youtube_error_code %>
</p>

<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>